INCLUDES+=-I/home/zach/zach/opt/kodi-android/xbmc/cores/VideoPlayer

SRCS  = DVDCodecUtils.cpp
SRCS += DVDFactoryCodec.cpp

LIB=	DVDCodecs.a

include /home/zach/zach/opt/kodi-android/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

