SET(APP_NAME RoBoXTV)
SET(APP_NAME_LC roboxtv)
SET(APP_NAME_UC ROBOXTV)
SET(APP_VERSION_MAJOR 1)
SET(APP_VERSION_MINOR 0)
IF(NOT ROBOXTV_PREFIX)
  SET(ROBOXTV_PREFIX /home/zach/zach/opt/xbmc-depends/arm-linux-androideabi-android-17)
ENDIF()
IF(NOT ROBOXTV_INCLUDE_DIR)
  SET(ROBOXTV_INCLUDE_DIR /home/zach/zach/opt/xbmc-depends/arm-linux-androideabi-android-17/include/roboxtv)
ENDIF()
IF(NOT ROBOXTV_LIB_DIR)
  SET(ROBOXTV_LIB_DIR /home/zach/zach/opt/xbmc-depends/arm-linux-androideabi-android-17/lib/roboxtv)
ENDIF()
IF(NOT WIN32)
  SET(CMAKE_CXX_FLAGS "$ENV{CXXFLAGS} ")
ENDIF()
LIST(APPEND CMAKE_MODULE_PATH /home/zach/zach/opt/xbmc-depends/arm-linux-androideabi-android-17/lib/roboxtv)
ADD_DEFINITIONS(-DTARGET_POSIX -DTARGET_LINUX -D_LINUX -DTARGET_ANDROID -DBUILD_KODI_ADDON)

if(NOT CORE_SYSTEM_NAME)
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(CORE_SYSTEM_NAME "osx")
  else()
    string(TOLOWER ${CMAKE_SYSTEM_NAME} CORE_SYSTEM_NAME)
  endif()
endif()

include(addon-helpers)
