SRCS  = CDDARipJob.cpp
SRCS += CDDARipper.cpp
SRCS += Encoder.cpp
SRCS += EncoderFFmpeg.cpp

LIB=cdrip.a

include /home/zach/zach/opt/kodi-android/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
