SRCS  = PlayerCoreFactory.cpp
SRCS += PlayerSelectionRule.cpp

LIB = playercorefactory.a

include /home/zach/zach/opt/kodi-android/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

